name: simulated_web_agent
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9
  - ipykernel
  - openjdk=11
  - ca-certificates
  - openssl
  - pip:
      - annotated-types==0.7.0
      - anyio==4.4.0
      - attrs==23.2.0
      - beautifulsoup4==4.12.3
      - blis==0.7.11
      - catalogue==2.0.10
      - certifi==2024.7.4
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpathlib==0.18.1
      - cloudpickle==3.0.0
      - coloredlogs==15.0.1
      - confection==0.1.5
      - cymem==2.0.8
      - cython==3.0.10
      - distro==1.9.0
      - dominate==2.9.1
      - exceptiongroup==1.2.2
      - faiss-cpu==1.8.0.post1
      - farama-notifications==0.0.4
      - filelock==3.15.4
      - flatbuffers==24.3.25
      - fsspec==2024.6.1
      - gymnasium==0.29.1
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.24.0
      - humanfriendly==10.0
      - idna==3.7
      - ipywidgets==8.1.3
      - jinja2==3.1.4
      - joblib==1.4.2
      - jupyterlab-widgets==3.0.11
      - langcodes==3.4.0
      - language-data==1.2.0
      - lightgbm==4.4.0
      - marisa-trie==1.2.0
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - mdurl==0.1.2
      - mpmath==1.3.0
      - murmurhash==1.0.10
      - networkx==3.2.1
      - nmslib==2.1.1
      - numpy==1.26.4
      - onnxruntime==1.18.1
      - openai==1.35.15
      - outcome==1.3.0.post0
      - pandas==2.2.2
      - preshed==3.0.9
      - protobuf==5.27.2
      - pybind11==2.6.1
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pyjnius==1.6.1
      - pyserini==0.17.0
      - pysocks==1.7.1
      - pytz==2024.1
      - pyyaml==6.0.1
      - regex==2024.5.15
      - requests==2.32.3
      - rich==13.7.1
      - safetensors==0.4.3
      - scikit-learn==1.5.1
      - scipy==1.13.1
      - selenium==4.23.1
      - sentencepiece==0.2.0
      - shellingham==1.5.4
      - smart-open==7.0.4
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.5
      - spacy==3.7.5
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.4.8
      - sympy==1.13.0
      - thinc==8.2.5
      - threadpoolctl==3.5.0
      - tokenizers==0.19.1
      - tqdm==4.66.4
      - transformers==4.42.4
      - trio==0.26.0
      - trio-websocket==0.11.1
      - typer==0.12.3
      - tzdata==2024.1
      - urllib3==2.2.2
      - wasabi==1.1.3
      - weasel==0.4.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.11
      - wrapt==1.16.0
      - wsproto==1.2.0
